spring:
  profiles:
    active: @spring.profiles.active@
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  tomcat:
    max-http-form-post-size: 20MB
application:
  title: HarvestShare
  version: 1.0